### ISSUE TITLE
Adapt frontend to the new contract

### ISSUE THREAD

**Issue by kaisbaccour** [noislabs/randdrop-ui#1]
First the user 
- opens the UI to participate
- connects the wallet
- see their juno or whatever network the randdrop contract they are on
- The frontend checks if the juno address is on the github list and if they are a participate button is enabled
- The user clicks on participate, so the frontend downloads the randdrop file,  and generates the proof then sends it to the randdrop contract with a message similar to this. 
` '{"participate":{"amount":"74711941","proof":["c683e9ab4d7cffc52606aa3ee171d124ae9a57f05e351e6e2603dfce436487dc","ad23cc14faa5ac312e9d0ce8556adf2eec04aee3cb3c70c33bbb110e55c02da4","80101b58bd9ed6b38a96030ab786dd3e57fa4c54a0c719871239c731e4f3e452","8173ef4c7a10f807526d1c98d9dc3f31c1e1573d91e1a277f0d2402ae9f2a5a6","1a8f1619448c2c5968c4f58cd78fe6fc3dba749de36c13f45ac8d541ae192d20","a5f77a7ce77940a5f68af5ffe3992532d6178f23fdbc1238f5f84fab5cfa7243","a7a1fdeea81e9a4b1a6b58703cc1da3f2dd1ae309734b69bd1caa00e321ee247","477a2f2885e39be7a0c76c4a766c5ffa6a28bae066b58bbb868f9f008e6c4899","50b409286902a470c10d1aac1014182606a587033a120cc71d49ea9974123bc3","723f2b84752aae6f6243f54627d88169bcea8fa9d233accce2779bcab0d6cbfa","3f1dca55c55b0feab7d40629d20e3f4a90dc908d129b628eff4a99219ca0782d","49de319f3d929c6c7e6fd247bd84db8519d45b947afe92d0f7866a6d3fbf6d16","a10acecae9b1c8dc795dee423f56fcc457a6f8ab567c0070eb33b4a6ed5913e2","bda76c1358d096c74780011ebafc99b1af58ed51ee258a4013dd17b90240f63b","471a3872ad818e02be2145a90d9558601311f88ecf556383c4b017627007c7b2","669627ae91df85a1e236fee0b1ae2d65256d471e0307f34215574f54f6e26b8a","e004b23a35d1994359a27f225cf2024f59325e24f4667c7bd6a2230c97d5e3bd"]}}'`
- there is some animation (dice rolling or whatever) waiting for the randomness to happen.
- In the meantime the contract can make this command to check the data of the participant
` '{"participant":{"address":"juno1etltrk88jyye62lynfd8e8zhnu0lxd9udsk8fc"}}'` . This command tells you if the player has already participated, or if the randomness came or not, and if the user won or not.
- upon randomness reception tell the user if they won or not.

New randdrop contract address: `juno13qtdjhhltza8w2972fchk7fdkareadesat0907vfz6za7v84tznqr2uazr`

**Comment by LeTurt333** [comment]
I think it would be better to do the checks up front when a user connects their wallet, that we we don't have to generate the proof unless it's needed. The flow would be like this:

### **User arrives to website**
- Chain Selector is available
- User is prompted with `Connect Wallet to check eligibility`

### **When wallet is connected**
- Check if address is on github list
  - `True?` -> Continue
  - `False?` -> Error message "Not eligible" && break
- Check if address has already participated
  - `True && User won` -> Confetti + Info message "Already Claimed, check your wallet balance!" && break
  - `True && User didn't win` -> Info message "Did not win sorry" && break
  - `False` -> Continue
- Check if still waiting on randomness
  - `True` -> Info message "Still waiting" + Dice animation && break
  - `False` -> Generate proof && enable "Roll Dice" button
  
### **When "Roll Dice" button is clicked**
- Check for proof && send claim message to contract
- Dice Animation

**Comment by kaisbaccour** [comment]
yes this is good 👍

**Comment by LeTurt333** [comment]
Added these in latest commit b2196e520827f00b378e20204a57c0e89c463781

I force pushed since the repos got separated, but at least its fixed now and it's good to have this in the Nois organization

I still have the Vercel deployment pointed to the old repo, in order to have it point to this one you have to add me to the Nois Vercel team

**Comment by LeTurt333** [comment]
This seems done so will close
