### ISSUE TITLE
Wallet icons are displayed too big

### ISSUE THREAD

**Issue by mnlytic** [noislabs/randdrop-ui#5]
OSX 13.3.1 (a) (22E772610a)
Brave Version 1.59.124 Chromium: 118.0.5993.117 (Official Build) (arm64)

<img width="880" alt="image" src="https://github.com/noislabs/randdrop-ui/assets/12068740/5045f5e5-b244-4826-9a3f-84ec8fd6bb0f">

**Comment by LeTurt333** [comment]
Updated in 7d2b278b21bc7eda40dd14408cd6f3729ed301b5
